### ISSUE TITLE
Mercator to lon lat infinite loop

### ISSUE THREAD

**Issue by Farkal** [fschutt/proj5#2]
The following code cause infinite loop.
```
let source_coordinates = CoordinateSource::CoordinateBuf(Box::new(
    CoordinateBuf {
        data: vec![(10.0, 0.0)],
        crs: Box::new(MercatorSystem),
        ellipsoid,
    }
));

let mut target_coordinates = CoordinateSource::LonLatBuf(Box::new(
LonLatBuf {
    data: Vec::with_capacity(2),
    ellipsoid,
}));

let mut strategy = MultithreadingStrategy::SingleCore;
source_coordinates.project(&mut target_coordinates, &mut strategy);
```
Why not using the proj 4 algorithm ? Just rewrite them in rust.
Here is the merc to lon lat conversion in proj4Js -> https://github.com/proj4js/proj4js/blob/8c29f6642b559daf2daada9788ff6aa01260ba44/lib/projections/merc.js#L71

**Comment by Farkal** [comment]
I write this code to convert merc to lon lat if it can help:
```
const RADIUS: f64 = 6378137.0;
pub fn merc_x_to_lon(x: f64) -> f64 {
    (x / RADIUS).to_degrees()
}

pub fn merc_y_to_lat(y: f64) -> f64 {
    360.0 * (y / RADIUS).exp().atan() / PI - 90.0
}

pub fn merc_to_lon_lat(x: f64, y: f64) -> (f64, f64) {
    (merc_x_to_lon(x), merc_y_to_lat(y))
}
```

**Comment by fschutt** [comment]
Because that's not a mercator projection, that's a web mercator projection. proj5 does an accurate, 6-point transformation. See https://en.wikipedia.org/wiki/Web_Mercator_projection#Advantages_and_disadvantages

I'll look into the infinite loop stuff.

**Comment by Farkal** [comment]
So how can i convert lon lat from 4326 to Web Mercator and convert Web Mercator to lon lat ?
What about implementing binding for the geo_types ? It would ease the convert process and also allow better integrations. (What about putting this crate to the georust team ?)
Any news about the infinite loop ?

**Comment by fschutt** [comment]
@Farkal The infinite loop issue has been fixed by https://github.com/fschutt/proj5/commit/9a2fa2ee8d89164a901ec20cd206f4b4f2efe206 - there was an issue with the break condition on the code translated from JS. Thank you for reporting. Updating `proj5` to `0.1.7` should fix the issue.

As for why I'm not implementing geo_types - I want to stay as dependency-free as possible in order to keep this repo easy to maintain. 

For reprojection, there is a `to_lon_lat` and `from_lon_lat` functions. See here for usage: 

https://github.com/fschutt/proj5/blob/54a1837b774ed1e694dc1a637e32d8d3a70ed3f6/src/coordinate_buf.rs#L47-L49

https://github.com/fschutt/proj5/blob/54a1837b774ed1e694dc1a637e32d8d3a70ed3f6/src/coordinate_buf.rs#L30-L33

I hope that answers your questions.
