### ISSUE TITLE
[Question:Usage] How can I use generic non-UTM CRS definition with proj5

### ISSUE THREAD

**Issue by usagi** [fschutt/proj5#3]
For example:

1. EPSG:31256 ; MGI / Austria GK East 👉 <https://epsg.io/31256>
2. EPSG:6680; JGD2011 / Japan Plane Rectangular CS XII 👉 <https://epsg.io/6680>

These are not a UTM CRS definitions. Could you show me a `crs:` definition example?

```rust
    let source_coordinates = CoordinateSource::CoordinateBuf(Box::new(
        CoordinateBuf {
            data: vec![(x, y)],
            crs: ???? // <-- Help, please.
            ellipsoid: ellipsoid,
        }
    ));
```

**Comment by fschutt** [comment]
Sorry, I was on vacation - currently not all transformations for coordinate systems are supported, the way that proj5 works is by translating to lat/lon, then translating back into the target coordinate system

So you'd have to do something like:

```rust
impl ToLatLon for AustriaGKEast {
   fn to_lon_lat(&self, mut data: Vec<(f64, f64)>, ellipsoid: Ellipsoid) -> LonLatBuf { ... }
}

impl FromLatLon for JGD2011 {
    fn from_lon_lat(&self, mut data: Vec<(f64, f64)>, ellipsoid: Ellipsoid) -> CoordinateBuf { ... }
}
```

Then you can transform from `AustriaGKEast` to `JGD2011`. That's basically all the framework does, auto-implementing the functions for chaining those two transforms. And then you can combine / mix and match coordinate systems, because all use lat-lon as a middle man.

**Comment by usagi** [comment]
I got it. Thanks for the answer.
